import { OAuth2Client } from 'google-auth-library'
import {
  GOOGLE_CLOUD_CREDENTIAL_WEB_CLIENT_CLIENT_ID,
  GOOGLE_CLOUD_CREDENTIAL_WEB_CLIENT_CLIENT_SECRET,
  GOOGLE_CLOUD_CREDENTIAL_WEB_CLIENT_REDIRECT_URL,
} from './constants'

export function createOAuth2Client(): OAuth2Client {
  return new OAuth2Client(
    GOOGLE_CLOUD_CREDENTIAL_WEB_CLIENT_CLIENT_ID,
    GOOGLE_CLOUD_CREDENTIAL_WEB_CLIENT_CLIENT_SECRET,
    GOOGLE_CLOUD_CREDENTIAL_WEB_CLIENT_REDIRECT_URL
  )
}
